name: Production build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
# Deploy a react web app to s3
#  build-frontend:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: frontend
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js
#      uses: actions/setup-node@v1
#      with:
#        node-version: "12.3.1"
#    - name: Yarn install
#      run: |
#        yarn install
#    - name: Tests
#      run: |
#        yarn test
#    - name: Build
#      run: |
#        yarn build
#    - name: Deploy to S3
#      uses: jakejarvis/s3-sync-action@master
#      with:
#        args: --acl public-read --delete
#      env:
#        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_REGION: ${{ secrets.AWS_REGION }}
#        SOURCE_DIR: "frontend/build"
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Covid19_Antibody_uk/serverless
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.3.1"
    - name: serverless deploy
      working-directory: Covid19_Antibody_uk/serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
      run: |
        npx serverless deploy --stage prod
